---

- name: Enable CodeReady Builder repository
  community.general.rhsm_repository:
    name: "codeready-builder-for-rhel-10-x86_64-rpms"
    state: enabled
  register: crb_enable

# - name: Import gpg key for epel
#   ansible.builtin.rpm_key:
#     state: present
#     key: "https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-10"

- name: Install EPEL repository for Rhel10
  ansible.builtin.dnf:
    name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-10.noarch.rpm"

...
